name: test-package
on: [push]


jobs:

  test-package:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pytest
        run: pip3 install pytest

      - name: Run tests
        run: pytest $GITHUB_WORKSPACE/test/
